### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by GnRSlash** [marcjoha/favicon#1]
Hi,

I`m trying to run your example but I got XMLHttpRequest error because of CORS.
If you try:   https://cors-anywhere.herokuapp.com/https://www.youtube.com/
Your code runs fine until this line:  if (await _verifyImage(iconUrl))
Because you get the icon url without cors

Is there a way to solve this?
Thank you
Slash

**Comment by marcjoha** [comment]
Hello there, apologies to keep you waiting! I just tried your example URL and the tool just returns null, which should be correct since there's no favicon on the URL you list. Closing the issue since I can't replicate, but please re-open if you the problem persists and you have more information.
