### ISSUE TITLE
No examples

### ISSUE THREAD

**Issue by OGmetamonkey** [marcjoha/favicon#2]
It would be extremely helpful to see an example project for this that actually displays the favicon. Any way to update the repo with one?

**Comment by marcjoha** [comment]
I've updated the readme with basic instructions -- since this is not a UI library there's really not that much to it.

**Comment by OGmetamonkey** [comment]
Ok. I suppose that was the confusion. The  example you provided provides a url. This doesn't actually return the icon, it returns the best url of an icon, correct? So you would have to retrieve it at that point using an http call?

**Comment by marcjoha** [comment]
Correct, it will return the url to the favicon with the largest dimensions. For displaying it you would indeed need to retrieve it yourself, but since this is platform specific I haven't implemented such code in this (dart-only) library.

For flutter, you can simply do ```Image.network(iconUrl)``` to return an image widget based on this.

**Comment by OGmetamonkey** [comment]
Great. Thank you! Also, I noticed the getBest() function throws an exception when there is no https:// prefix to the url. Any way around that that's already been implemented?

> Exception has occurred.
> ArgumentError (Invalid argument(s): No host specified in URI infocert.digital)

**Comment by marcjoha** [comment]
Can you give me a code example that reproduce that issue?

**Comment by OGmetamonkey** [comment]
```
import 'package:favicon/favicon.dart' as iconz;

var urlUse;

void initState() {
    super.initState();
    urlUse = iconsGet("google.com");
}

Future<Null> iconsGet(String url) async {
  return Future.value(iconz.Favicon.getBest(url));
}
```

> Exception has occurred.
> ArgumentError (Invalid argument(s): No host specified in URI google.com)

Also tried changing the function to a more simple:
`return iconz.Favicon.getBest(url);`

Same result.

**Comment by OGmetamonkey** [comment]
This may be due to an html error with flutter default settings. Any idea?
