### ISSUE TITLE
"Icon" name conflict

### ISSUE THREAD

**Issue by saropa** [marcjoha/favicon#6]
Hi, the class defined here called "Icon" conflicts with Flutter's own "Icon" (ref: https://api.flutter.dev/flutter/widgets/Icon-class.html) making this package difficult to implement.

**Comment by And96** [comment]
Yes. I got the same problem.

You can use "hide icon" after the references to the package in the top of mai.dart file

**Comment by marcjoha** [comment]
Hey folks, thanks for the input. Would this work for you? https://github.com/marcjoha/favicon/pull/7

**Comment by saropa** [comment]
Looks good, and I'd be happy to try the package again!

**Comment by marcjoha** [comment]
Ack, merged and will push a new version to pub.dev immediately.
