### ISSUE TITLE
Feature request - Get Icon with lowest resolution

### ISSUE THREAD

**Issue by And96** [marcjoha/favicon#8]
Is possible to add a function to get the opposite of "getBest()" ?

.ICO file are often much smaller than .PNG tipically 16x16
It's just for performance purpose
With a long list of 10k+ item, optimization make a lot of differences

Great dart package!

**Comment by marcjoha** [comment]
Since `getBest()` is actually just `getAll(url).first` so you can already do this with `getAll(url).last`. Does that work for you?

**Comment by And96** [comment]
Yeah! That's work. Thanks

But it's still pretty slow. 
IDK if you may have some ideas for performance improvement... Actually it takes about about 1 second per site.
With 50+ differents sites. It takes about 1 minute to start the app.
I can start instantly since 2nd run caching icons.

Your package works fine. I am looking for something to improve performance. Maybe skipping "_verifyImage" or something

**Comment by And96** [comment]
Example: 

slow: https://news.google.com ( >5 seconds )

fast: https://google.com ( <1 second )

**Comment by And96** [comment]
Some ideas?

**Comment by marcjoha** [comment]
It should be possible to parallelize the downloads before comparison. If
you take a stab feel free to open a pull request.

However, it sounds like if you're using this lib when opening your app you
should perhaps cache results?

Anyway, closing this issue since it's about resolution size.

**Comment by And96** [comment]
Ok. Thanks
