### ISSUE TITLE
Can update image dependancy?

### ISSUE THREAD

**Issue by saropa** [marcjoha/favicon#9]
Hi, thanks for the package!

The favicon "image" dependancy is out of date and so has starting causing conflicts. Can you version-bump if possible?

Thanks,

ref: https://pub.dev/packages/image/changelog (image is at ver 4.0.10 vs 3.0.2 in the current pubspec)

**Comment by marcjoha** [comment]
You got it! New version live on pub.dev now.

**Comment by saropa** [comment]
Thanks so much!
